<link rel="stylesheet" href="{{ '/assets/css/responsive.css' | relative_url }}">

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
<meta name="viewport" content="width=device-width, initial-scale=1.0">

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about
  - title: "Artifacts"
    url: /artifacts
  - title: "Resume"
    url: /resume
  - title: "Awards & Honors"
    url: /awards
  - title: "Career"
    url: /career
  - title: "Code Review"
    url: /code-review
  - title: "Self Assessment"
    url: /self-assessment

